Build cpio from git fails

diff --git a/core/scripts/includes/build-options b/core/scripts/includes/build-options
--- a/core/scripts/includes/build-options
+++ b/core/scripts/includes/build-options
@@ -166,6 +166,8 @@ echo $ARCHIVE | grep FreeRDP &&  LC_CONFIGURE_OPTS="-DCMAKE_INSTALL_PREFIX=$DIBA
         -Wno-dev "
 echo $ARCHIVE | grep gegl-0 &&  LC_CONFIGURE_OPTS="-Ddocs=false "
 echo $ARCHIVE | grep gegl-0 && [ -e $HOME/$ARCH/share/gir-1.0/Babl-0.1.gir ] && [ ! -e $HOME/$ARCH/share/gir-1.0/babl-0.1.gir ] && cp $HOME/$ARCH/share/gir-1.0/Babl-0.1.gir $HOME/$ARCH/share/gir-1.0/babl-0.1.gir
+echo $ARCHIVE | grep gobject-introspection && cp gir/* $HOME/$ARCH/share/gir-1.0
+echo $ARCHIVE | grep gobject-introspection && [ ! -e $HOME/$ARCH/share/gir-1.0/GObject-2.0.gir ] && echo "Missing $HOME/$ARCH/share/gir-1.0/GObject-2.0.gir" && exit 2
 echo $ARCHIVE | grep ostree &&  LC_CONFIGURE_OPTS="--with-openssl --disable-otmpfile"
 echo $ARCHIVE | grep tracker-3 &&  LC_CONFIGURE_OPTS="-Ddocs=false -Dman=false"
 echo $ARCHIVE | grep caca &&  LC_CONFIGURE_OPTS="--disable-java --disable-doc"
