Build multilib

diff --git a/2.12/scripts/make_initramfs b/2.12/scripts/make_initramfs
--- a/2.12/scripts/make_initramfs
+++ b/2.12/scripts/make_initramfs
@@ -49,27 +49,28 @@ add_file() {
 
 
 add_module() {
-        if modinfo -k $KERNEL $1 >/dev/null 2>&1; then
-                modname=$(modinfo -k $KERNEL -F name $1 | cut -d ' ' -f1 | head -n1)
+        # echo modinfo -b $KERNEL_MODULES_PATH -k $KERNEL $1 
+        if modinfo -b $KERNEL_MODULES_PATH -k $KERNEL $1 >/dev/null 2>&1; then
+                modname=$(modinfo -b $KERNEL_MODULES_PATH -k $KERNEL -F name $1 | cut -d ' ' -f1 | head -n1)
                 [ "$modname" = "name:" ] && return 0
-                modpath=$(modinfo -k $KERNEL -F filename $1 | cut -d ' ' -f1 | head -n1)
+                modpath=$(modinfo -b $KERNEL_MODULES_PATH -k $KERNEL -F filename $1 | cut -d ' ' -f1 | head -n1)
                 [ "$modpath" = "name:" ] && return 0
         else
-                msg "missing module: $1"
+                echo "missing module: $1" && exit 2
                 return
         fi
         if [ -f $INITDIR/lib/modules/$KERNEL/kernel/${modpath##*/} ]; then
                 return
         fi
         add_file "$modpath" lib/modules/$KERNEL/kernel/${modpath##*/}
-        modinfo -F firmware -k $KERNEL $modname | while read -r line; do
+        modinfo -b $KERNEL_MODULES_PATH -F firmware -k $KERNEL $modname | while read -r line; do
                 if [ ! -f /lib/firmware/$line ]; then
                         msgwarn "missing firmware for $modname: $line"
                 else
                         add_file /lib/firmware/$line
                 fi
         done
-        for i in $(modinfo -F depends -k $KERNEL $modname | tr ',' ' '); do
+        for i in $(modinfo -b $KERNEL_MODULES_PATH -F depends -k $KERNEL $modname | tr ',' ' '); do
                 add_module $i
         done
         unset modname modpath
@@ -154,11 +155,22 @@ KERNEL=$KERNEL3
                 kernel/drivers/usb/storage"
 
 	for mod in $REQMODULES; do
-		FTGT="$FTGT /lib/modules/$(uname -r)/$mod"
+    if [ "$KERNEL" = "KERNEL3" ]
+    then
+		  FTGT="$FTGT /lib/modules/$(uname -r)/$mod"
+    else
+		  FTGT="$KERNEL_MODULES_PATH/lib/modules/$KERNEL3"
+    fi   
+    echo "FTGT : $FTGT"
 	done
 	for modules in $(find $FTGT -type f -name "*.ko*" 2> /dev/null); do
 		modules=$(echo ${modules%*.ko*})
-		INITDIR=$HOME/ydfs/tmp/initramfs-$ARCH/ KERNEL=$(uname -r) add_module ${modules##*/}
+    if [ "$KERNEL" = "KERNEL3" ]
+    then
+		  INITDIR=$HOME/ydfs/tmp/initramfs-$ARCH/ KERNEL=$(uname -r) add_module ${modules##*/}
+    else
+		  INITDIR=$HOME/ydfs/tmp/initramfs-$ARCH/ KERNEL=$KERNEL add_module ${modules##*/}
+    fi
 	done
 
   cp $HOME_DIBAB/dev-initramfs.cpio $HOME/ydfs/build-$ARCH/initramfs
diff --git a/2.12/scripts/make_multilib b/2.12/scripts/make_multilib
--- a/2.12/scripts/make_multilib
+++ b/2.12/scripts/make_multilib
@@ -19,7 +19,7 @@ install -d $HOME/multilib/include
 [ ! -e $HOME/multilib/lib32 ] && ln -s $HOME/$ARCH/lib32 $HOME/multilib/lib32
 [ ! -e $HOME/multilib/lib ] && ln -s $HOME/$ARCH/lib32 $HOME/multilib/lib
   
-PKGMULTILIB="zlib-1 gmp xz-5 libunwind libunistring libtasn1 libidn nettle xorgproto alsa-lib ncurses readline libxcrypt pcre- pcre2 tcl8 sqlite util-linux libpng-1.2 libpng-1.6 libffi p11-kit zstd gnutls openssl-1 curl elfutils expat dbus-1.12.20 glib freetype-2 icu harfbuzz freetype-2 json-c fontconfig-2 \
+PKGMULTILIB="zlib-1 gmp xz-5 libunwind libunistring libtasn1 libidn nettle xorgproto alsa-lib ncurses readline libxcrypt pcre- pcre2 tcl8 sqlite libcap-ng util-linux libpng-1.2 libpng-1.6 libffi p11-kit zstd gnutls openssl-1 curl elfutils expat dbus-1.12.20 glib freetype-2 icu harfbuzz freetype-2 json-c fontconfig-2 \
 xtrans libXau libpthread-stubs xcb-proto libxcb \
 libX11-1 \
 libXext-1 \
@@ -185,6 +185,9 @@ unset MAKE
     -D tests=true \
     -D introspection=false || exit 1
         ;;
+    libcap-ng )
+	./configure --prefix=$HOME/multilib --without-python3 --without-python
+	;;
     kmod )
 	./configure --prefix=$HOME/multilib --disable-manpages
 	;;
@@ -287,9 +290,6 @@ unset MAKE
     icu )
 	cd source
   	./configure --prefix=$HOME/multilib || exit $?
-    ;;
-    util-linux* )
-  	./configure --without-python --without-systemd --disable-makeinstall-chown --prefix=$HOME/multilib || exit $?
     ;;
     dbus-1.12.20 )
   	./configure --prefix=$HOME/multilib  --disable-verbose-mode --disable-static --disable-tests --disable-asserts --disable-systemd || exit $?
@@ -461,6 +461,12 @@ unset MAKE
 	cd build-32
         PYTHONPATH="" meson ../ --prefix=$HOME/multilib -Dintrospection=no --libdir=$HOME/multilib/lib32 || exit 1
 	;;
+     util-linux )
+  [ -e build-32 ] && rm -fR build-32
+	mkdir build-32
+	cd build-32
+        PYTHONPATH="" meson ../ --prefix=$HOME/multilib -Dtty-setgid=false -Dncurses=disabled -Dncursesw=disabled -Dbuild-libmount=disabled -Dcryptsetup=disabled --libdir=$HOME/multilib/lib32 --libexecdir=$HOME/multilib/lib32 || exit 1
+	;;
      libgudev | libsoup-2 | pango-1 )
 	mkdir build-32
 	cd build-32
@@ -543,7 +549,7 @@ unset MAKE
 	cp libbz2.so.1.0 $HOME/multilib/lib
 	ln -s libbz2.so.1.0 $HOME/multilib/lib/libbz2.so
 	;;
-    libvdpau | json-glib | libgudev | glib-networking | libsoup-2 | polkit-1 | wayland-1 | pulseaudio-14 | p11-kit | gst-plugins-base|polkit-0|libgusb|colord|at-spi2-core|at-spi2-atk | libxkbcommon | libepoxy | gstreamer-1 | glib | libdrm | mesa-2 | libglvnd | pango-1 | atk-2 | gdk-pixbuf | libvdpau)
+    libvdpau | json-glib | libgudev | glib-networking | libsoup-2 | polkit-1 | wayland-1 | pulseaudio-14 | p11-kit | gst-plugins-base|polkit-0|libgusb|colord|at-spi2-core|at-spi2-atk | libxkbcommon | libepoxy | gstreamer-1 | glib | libdrm | mesa-2 | libglvnd | util-linux | pango-1 | atk-2 | gdk-pixbuf | libvdpau)
   echo "Run Ninja" 
         PYTHONPATH="" ninja || exit 1
 	;;
@@ -569,7 +575,7 @@ unset MAKE
 	;;
    llvm )
 	;;
-   libvdpau | json-glib | libgudev | glib-networking | libsoup-2 | polkit-1 | wayland-1 | pulseaudio-14 | p11-kit | gst-plugins-base|polkit-0|libgusb|colord|+-3|at-spi2-core|at-spi2-atk|libxkbcommon | libepoxy | gstreamer-1 | glib | mesa-2 | libdrm | libglvnd | pango-1 | atk-2 | gdk-pixbuf )
+   libvdpau | json-glib | libgudev | glib-networking | libsoup-2 | polkit-1 | wayland-1 | pulseaudio-14 | p11-kit | gst-plugins-base|polkit-0|libgusb|colord|+-3|at-spi2-core|at-spi2-atk|libxkbcommon | libepoxy | gstreamer-1 | glib | mesa-2 | libdrm | libglvnd | util-linux | pango-1 | atk-2 | gdk-pixbuf )
   	echo "Do nothing for $PKG"
 	;;
     * )
@@ -604,6 +610,11 @@ unset MAKE
     libvdpau | json-glib | libgudev | glib-networking | libsoup-2 | polkit-1 | wayland-1 | pulseaudio-14 | p11-kit | gst-plugins-base|polkit-0|libgusb|colord|at-spi2-core|at-spi2-atk|libxkbcommon | libepoxy | gstreamer-1 | glib | libdrm | libglvnd | pango-1 | atk-2 | gdk-pixbuf)
   	echo "Run ninja install "
         PYTHONPATH="" ninja install || exit 1
+	cd ..
+	;;
+    util-linux)
+  	echo "Run ninja install fail and continue "
+        PYTHONPATH="" ninja install 
 	cd ..
 	;;
     * )
